export enum APP_ERROR_CODE {
  UNAUTHORIZED = 'APP_401',
  FORBIDDEN = 'APP_403',
  BAD_REQUEST = 'APP_400',
  NOT_FOUND = 'APP_404',
  INTERNAL_ERROR = 'APP_500',
  VALIDATION_FAILED = 'APP_422',
  USER_NOT_FOUND = 'APP_423',
  CONFLICT = 'APP_409',
}
